[workspace]

members = [
        "cli", # frontend binary
        "compiler", # compiler library
        "wasm", # web frontend
]


[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"